### ISSUE TITLE
Can't create asana connector in Cohere

### ISSUE THREAD

**Issue by llermaly** [cohere-ai/quick-start-connectors#132]
### Which connector is affected?

Asana

### What is the issue?

I'm able to hit my connector URL with postman: 

```
curl --location 'https://<my_url>/search' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ey.....' \
--data '{
    "query": "design"
  }'
```

Now I'm trying to create it on Cohere with no luck: 

```
import dotenv from "dotenv";
dotenv.config();

import { CohereClient } from "cohere-ai";

const cohere = new CohereClient({
  token: process.env.COHERE_API_KEY,
});


(async () => {
  const connector = await cohere.connectors.create({
    name: "asana-connector",
    url: "https://<my_url>/search",
    description: "Asana connector",
    service_auth: {
      type: "bearer",
      token: process.env.ASANA_CONNECTOR_TOKEN,
    },
  });

  console.log(connector);
})();

```

Both API keys are in place, I tried hardcoding them.

This is the error: 

```
BadRequestError: BadRequestError
Status code: 400
Body: {
  "message": "connector not reachable at https://<my_url>/search. error: request failed with status code 401"
}
  statusCode: 400,
  body: {
    message: 'connector not reachable at https://<my_url>/search. error: request failed with status code 401'
  }
}
```

Any ideas? 

I'm following this documentation:

https://docs.cohere.com/reference/create-connector

Thanks

**Comment by llermaly** [comment]
It seems that is related to the JS library. cURL direct worked 👍 

```
curl --location 'https://api.cohere.ai/v1/connectors' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer xpN....' \
--data '{
    "name": "connector",
    "url": "https://<my_url>/search",
    "service_auth": {
        "type": "bearer",
        "token": "eyJh....."
    }
}'
```

**Comment by tianjing-li** [comment]
Indeed, this looks like an issue with the JS client - thanks for opening that!

**Comment by fenilsuchak** [comment]
@llermaly @tianjing-li, I see the same issue with Python SDK, curl seems to be working fine.

```
Traceback (most recent call last):
  File "/Users/fsuchak/Desktop/cohere_main/quick-start-connectors/oracleadb/e2e_test.py", line 6, in <module>
    created_connector = co.connectors.create(
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fsuchak/Desktop/cohere_main/quick-start-connectors/oracleadb/.venv/lib/python3.11/site-packages/cohere/connectors/client.py", line 175, in create
    raise BadRequestError(
cohere.errors.bad_request_error.BadRequestError: status_code: 400, body: {'message': 'connector not reachable at https://oracleadb-connector-p5qc6cr5tq-uc.a.run.app/search. error: request failed with status code 401'}
```
